name              'perl'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Provides resources to install Perl and maintain CPAN modules'
version           '8.0.21'
source_url        'https://github.com/sous-chefs/perl'
issues_url        'https://github.com/sous-chefs/perl/issues'
chef_version      '>= 15.3'

supports 'almalinux', '>= 8.0'
supports 'amazon', '>= 2023.0'
supports 'centos_stream', '>= 9.0'
supports 'debian', '>= 12.0'
supports 'fedora'
supports 'freebsd'
supports 'oracle', '>= 8.0'
supports 'redhat', '>= 8.0'
supports 'rocky', '>= 8.0'
supports 'smartos'
supports 'ubuntu', '>= 22.04'
supports 'windows'
supports 'zlinux'
