name              'perl'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Installs perl and provides a resource for maintaining CPAN modules'
version           '8.0.0'
source_url        'https://github.com/sous-chefs/perl'
issues_url        'https://github.com/sous-chefs/perl/issues'
chef_version      '>= 15.3'

supports 'amazon'
supports 'centos'
supports 'debian'
supports 'fedora'
supports 'freebsd'
supports 'linuxmint'
supports 'opensuse'
supports 'opensuseleap'
supports 'oracle'
supports 'redhat'
supports 'scientific'
supports 'smartos'
supports 'suse'
supports 'ubuntu'
supports 'windows'
supports 'zlinux'
